# Pandas Advanced Lesson

### Combining series and dataframes
- `pd.concat()` : Allows to add dataframes together of similar shapes
- `pd.append()`
- `pd.merge()`
- `pd.join()`

In [1]:
import pandas as pd
import numpy as nb

In [2]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },

)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },

)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },

)

In [ ]:
frames = [df1, df2, df3]
# ignore_index to create a new index starting from 0 to end
result = pd.concat(frames, ignore_index=True)

In [6]:
result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
# keys= delineates the different concatenated df
# allows tracking of original df
result = pd.concat(frames, keys=['X', 'Y', 'Z'])

In [8]:
result

       A    B    C    D
X 0   A0   B0   C0   D0
  1   A1   B1   C1   D1
  2   A2   B2   C2   D2
  3   A3   B3   C3   D3
Y 0   A4   B4   C4   D4
  1   A5   B5   C5   D5
  2   A6   B6   C6   D6
  3   A7   B7   C7   D7
Z 0   A8   B8   C8   D8
  1   A9   B9   C9   D9
  2  A10  B10  C10  D10
  3  A11  B11  C11  D11

In [ ]:
# extracts the original df objects
result_y = result.loc[('Y')]

result_y

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [10]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[12, 13, 14, 15],
)

df4

     B   D   F
12  B2  D2  F2
13  B3  D3  F3
14  B6  D6  F6
15  B7  D7  F7

In [14]:
result = pd.concat((df1, df4), ignore_index=True, sort=False)

result

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [16]:
result = pd.concat((df1, df4), ignore_index=True, axis=1, sort=False)
result

      0    1    2    3    4    5    6
0    A0   B0   C0   D0  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN
12  NaN  NaN  NaN  NaN   B2   D2   F2
13  NaN  NaN  NaN  NaN   B3   D3   F3
14  NaN  NaN  NaN  NaN   B6   D6   F6
15  NaN  NaN  NaN  NaN   B7   D7   F7

## Concatenating from seperate files

In [19]:
import pandas as pd
import numpy as np

In [20]:
re_df1 = pd.read_csv('data/RealEstate1.csv')
re_df2 = pd.read_csv('data/RealEstate2.csv')
re_df3 = pd.read_csv('data/RealEstate3.csv')

In [23]:
realestate = pd.concat((re_df1, re_df2, re_df3), axis=0, ignore_index=True)

In [24]:
realestate

,ID,MLS,Location,Price,Bedrooms,Bathrooms,Size,Price SQ Ft,Status
0,1,143178,Santa Maria-Orcutt,375000,4,2,1963,191.03,Short Sale
1,2,143217,Santa Maria-Orcutt,330000,3,3,1900,173.68,Short Sale
2,3,143252,Santa Maria-Orcutt,199000,3,3,1450,137.24,Short Sale
3,4,143255,Santa Maria-Orcutt,165000,2,2,1000,165.00,Short Sale
4,5,143436,Templeton,1399000,4,3,6500,215.23,Foreclosure
5,6,143507,Santa Maria-Orcutt,255000,3,2,1218,209.36,Short Sale
6,7,143524,Cambria,325000,2,2,893,363.94,Short Sale
7,8,143534,Morro Bay,789000,3,3,2100,375.71,Foreclosure
8,9,143540,Nipomo,498000,4,3,2341,212.73,Short Sale
9,10,143884,Nipomo,430000,4,2,2168,198.34,Short Sale
10,11,143946,Paso Robles,539900,4,3,3032,178.07,Short Sale
11,12,144204,Pismo Beach,499000,3,2,1293,385.92,Short Sale
12,12,144238,Los Osos,275000,3,2,1200,229.17,Short Sale

In [26]:
realestate[realestate.columns[1]]

0     143178
1     143217
2     143252
3     143255
4     143436
5     143507
6     143524
7     143534
8     143540
9     143884
10    143946
11    144204
12    144238
Name: MLS, dtype: int64

In [27]:
realestate['MLS']

0     143178
1     143217
2     143252
3     143255
4     143436
5     143507
6     143524
7     143534
8     143540
9     143884
10    143946
11    144204
12    144238
Name: MLS, dtype: int64

In [ ]:
rooms = realestate[realestate['Bedrooms'] > 3]

In [31]:
rooms

,ID,MLS,Location,Price,Bedrooms,Bathrooms,Size,Price SQ Ft,Status
0,1,143178,Santa Maria-Orcutt,375000,4,2,1963,191.03,Short Sale
4,5,143436,Templeton,1399000,4,3,6500,215.23,Foreclosure
8,9,143540,Nipomo,498000,4,3,2341,212.73,Short Sale
9,10,143884,Nipomo,430000,4,2,2168,198.34,Short Sale
10,11,143946,Paso Robles,539900,4,3,3032,178.07,Short Sale

## Merging

In [32]:
left_df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Fee' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

right_df = pd.DataFrame({'Courses': ["Java","PySpark","Python","pandas","Hyperion","html"],
                    'Fee': [20000,25000,30000,24000,40000,4000],
                    'Percentage':['10%','20%','25%','20%','10%','50%']})

In [33]:
left_df

   Courses    Fee Duration
0    Spark  20000    30day
1  PySpark  25000   40days
2   Python  30000   60days
3   pandas  24000   55days
4     Java  40000   50days

In [34]:
right_df

    Courses    Fee Percentage
0      Java  20000        10%
1   PySpark  25000        20%
2    Python  30000        25%
3    pandas  24000        20%
4  Hyperion  40000        10%
5      html   4000        50%

In [35]:
merged = pd.merge(left_df, right_df)
merged

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [36]:
merged = pd.merge(left_df, right_df, on='Courses')
merged

   Courses  Fee_x Duration  Fee_y Percentage
0  PySpark  25000   40days  25000        20%
1   Python  30000   60days  30000        25%
2   pandas  24000   55days  24000        20%
3     Java  40000   50days  20000        10%

In [ ]:
merged = pd.merge(left_df, right_df, on=['Courses','Fee'])
merged

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [42]:
# similar to sql left join
merged_df = pd.merge(
    left_df,
    right_df,
    how='left',
    left_on=['Courses', 'Fee'],
    right_on=['Courses', 'Fee']
)

merged_df

   Courses    Fee Duration Percentage
0    Spark  20000    30day        NaN
1  PySpark  25000   40days        20%
2   Python  30000   60days        25%
3   pandas  24000   55days        20%
4     Java  40000   50days        NaN

In [43]:
left = pd.DataFrame({"A": [1, 2], "B": [1, 2]})

right = pd.DataFrame({"A": [4, 5, 6], "B": [2, 2, 2]})

In [44]:
sales_data = {
    'TransactionID': [1, 2, 3, 4, 5],
    'ProductID': [101, 102, 103, 101, 105],
    'StoreID': [1, 2, 1, 3, 2],
    'Quantity': [5, 3, 2, 4, 1],
    'Amount': [500.00, 300.00, 200.00, 400.00, 150.00]
}

products_data = {
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Laptop', 'Headphones', 'Smartphone', 'Tablet', 'Monitor'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics']
}

## Joining

In [45]:
technologies = {
    'Courses':["Spark","PySpark","Python","pandas"],
    'Fee' :[20000,25000,22000,30000],
    'Duration':['30days','40days','35days','50days'],
              }
index_labels=['r1','r2','r3','r4']

technologies2 = {
    'Courses':["Spark","Java","Python","Go"],
    'Discount':[2000,2300,1200,2000]
              }
index_labels2=['r1','r6','r3','r5']

In [46]:
df1 = pd.DataFrame(technologies, index=index_labels)
df2 = pd.DataFrame(technologies2, index=index_labels2)

In [47]:
df1
df2

   Courses  Discount
r1   Spark      2000
r6    Java      2300
r3  Python      1200
r5      Go      2000

In [48]:
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right')

In [49]:
df3

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark    2000.0
r2      PySpark  25000   40days           NaN       NaN
r3       Python  22000   35days        Python    1200.0
r4       pandas  30000   50days           NaN       NaN

In [ ]:
# right join
df3 = df1.join(df2, lsuffix='_left', rsuffix='_right', how='inner')
df3

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark      2000
r3       Python  22000   35days        Python      1200

In [ ]:
# joining df and stting new indexes
df3 = df1.set_index('Courses').join(df2.set_index('Courses'), how='inner')

In [52]:
df3

           Fee Duration  Discount
Courses
Spark    20000   30days      2000
Python   22000   35days      1200

### AGGREGATION & GROUPING

- `df(series).aggregate(func)`